### ISSUE TITLE
stuck at stage3

### ISSUE THREAD

**Issue by flygyyy** [JianboGuo/network-decoupling#1]
Hello, the offical caffe dont include ConvolutionDepthwise layer and i download  it at https://github.com/farmingyard/caffe-mobilenet
the program progress well until the third stage, i dont if it is caused by the  ConvolutionDepthwise layer.
Can you offer the  ConvolutionDepthwise layer you use and if you have any suggestion?

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
stage3 loading new model and save
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
using GPU ID 0
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1117 21:35:48.485992  4124 net.cpp:296] The NetState phase (1) differed from the phase (0) specified by a rule in layer data
I1117 21:35:48.486460  4124 net.cpp:53] Initializing net from parameters: 
name: "VGG_ILSVRC_16_layers"
state {
  phase: TEST
  level: 0
}
......
I1117 21:35:48.701896  4124 net.cpp:124] Setting up relu1_1_relu1_1_0_split
I1117 21:35:48.701902  4124 net.cpp:131] Top shape: 10 64 224 224 (32112640)
I1117 21:35:48.701907  4124 net.cpp:131] Top shape: 10 64 224 224 (32112640)
I1117 21:35:48.701911  4124 net.cpp:131] Top shape: 10 64 224 224 (32112640)
I1117 21:35:48.701915  4124 net.cpp:131] Top shape: 10 64 224 224 (32112640)
I1117 21:35:48.701920  4124 net.cpp:131] Top shape: 10 64 224 224 (32112640)
I1117 21:35:48.701922  4124 net.cpp:139] Memory required for data: 905175200
I1117 21:35:48.701926  4124 layer_factory.hpp:77] Creating layer conv1_2_D4
I1117 21:35:48.701936  4124 net.cpp:86] Creating Layer conv1_2_D4
I1117 21:35:48.701939  4124 net.cpp:408] conv1_2_D4 <- relu1_1_relu1_1_0_split_0
I1117 21:35:48.701946  4124 net.cpp:382] conv1_2_D4 -> conv1_2_D4

**Comment by flygyyy** [comment]
I have test the ResNet-18 model, it works well. But I dont know why VGG16 cant work?

**Comment by JianboGuo** [comment]
@flygyyy Sorry for my long delay. I have asked one of my colleague [Yuxi Li](https://github.com/lyxok1) for the depthwise conv caffe C++ code. Actually, in our experiments, we did not suffer from such errors, and VGG16 always works.

**Comment by JianboGuo** [comment]
@flygyyy I have uploaded the conv_dw C++ code. Please see [here](https://github.com/JianboGuo/network-decoupling/tree/master/dw_conv)

**Comment by flygyyy** [comment]
@JianboGuo 
Thanks for your feedback, I have tested the code and the vgg net also works well.
Best regards!
